services:
  db:
    container_name: postgres
    image: postgres
    env_file:
      - ./.env
    volumes:
      - ./containers/db:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    restart: unless-stopped

  pgadmin:
    restart: always
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - ./.env
    depends_on:
      - db
    volumes: 
      - ./containers/pgadmin:/var/lib/pgadmin/
    ports:
      - "4000:80"

  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - ./.env
    volumes:
      - ./containers/redis-data:/data
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    container_name: backend
    volumes:
      - ./:/app/
    ports:
      - "3050:3050"
    depends_on:
      - db
      - redis

  migrate:
    image: migrate/migrate
    container_name: migrate
    volumes: 
      - ./internal/migrations/:/migrations/
    env_file: 
      - ./.env
    command: ["-path", "/migrations", "-database", "${DATABASE_URL}", "up"]
    depends_on:
      - db
      - backend
      - redis
      - pgadmin
    restart: unless-stopped