ALTER TABLE pair_requests ADD COLUMN created_at TIMESTAMP DEFAULT NOW() NOT NULL;
ALTER TABLE pair_requests ADD COLUMN updated_at TIMESTAMP DEFAULT NOW() NOT NULL;

ALTER TABLE friends ADD COLUMN created_at TIMESTAMP DEFAULT NOW() NOT NULL;
ALTER TABLE friends ADD COLUMN updated_at TIMESTAMP DEFAULT NOW() NOT NULL;